ORC-754: Code cleanup
apache/orc pull request #646
Opened 2021-02-23 22:43 UTC by pavibhai

* Removal of group name in bench pom.xml
* Replaced Charset.forName with StandardCharsets
* Final on some variables
* Removed final on a private method
* Simplified some conditions
* Removed redundant casts
* Removed duplicate condition branches

### What changes were proposed in this pull request?

### Why are the changes needed?

### How was this patch tested?

2021-02-23 23:03 UTC, omalley requested changes
This is a good set of changes, but I don't think we need the bench pom change.

2021-02-23 23:04 UTC, pavibhai commented on java/bench/core/pom.xml
> +        </configuration>
agreed

2021-02-23 23:48 UTC, omalley commented
I just committed this. Thanks, Pavan!

2021-02-23 23:49 UTC, merged

2021-02-25 02:19 UTC, dongjoon-hyun commented
Thank you, @pavibhai and @omalley .